export type SerializedTrackingMode =
  | 'single-card'
  | 'multi-card-treatment'
  | 'variant-card'
  | 'promo-series';

export type SerializedCatalogStatus = 'live' | 'planned' | 'announced' | 'needs-verification';

export interface SerializedSerialVariant {
  label: string;
  total: number;
}

export interface SerializedCatalogEntry {
  slug: string;
  title: string;
  setCode: string;
  setName: string;
  releaseYear?: number;
  releaseMonth?: string;
  treatment: string;
  trackingMode: SerializedTrackingMode;
  status: SerializedCatalogStatus;
  cardCount: number;
  numbered?: string;
  foundIn?: string;
  defaultSerialTotal?: number;
  serialVariants?: SerializedSerialVariant[];
  sampleCards: string[];
  scryfallQuery: string;
  notes?: string;
  sourceUrls: string[];
}

export const serializedCatalog: SerializedCatalogEntry[] = [
  {
    slug: 'secret-lair-mirrored-viscera-seer',
    title: 'Mirrored Viscera Seer',
    setCode: 'SLD',
    setName: 'Secret Lair Drop',
    releaseYear: 2021,
    releaseMonth: '2021-11',
    treatment: 'serialized Secret Lair promo',
    trackingMode: 'single-card',
    status: 'needs-verification',
    cardCount: 1,
    numbered: '1-100',
    foundIn: 'Bonus card for Phyrexian Praetors: Compleat Edition',
    defaultSerialTotal: 100,
    sampleCards: ['Viscera Seer'],
    scryfallQuery: 'set:sld is:serialized "Viscera Seer"',
    notes: 'Quantity should be verified against primary Secret Lair documentation before launch.',
    sourceUrls: ['https://scryfall.com/search?q=set%3Asld+is%3Aserialized'],
  },
  {
    slug: 'bro-retro-schematic-artifacts',
    title: "The Brothers' War Retro Schematic Artifacts",
    setCode: 'BRR',
    setName: "The Brothers' War Retro Artifacts",
    releaseYear: 2022,
    releaseMonth: '2022-11',
    treatment: 'serialized schematic retro artifacts',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 63,
    numbered: '1-500',
    foundIn: "Collector Boosters of The Brothers' War",
    defaultSerialTotal: 500,
    sampleCards: ['Aetherflux Reservoir', "Ashnod's Altar", 'Chromatic Lantern'],
    scryfallQuery: 'set:brr is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Abrr+is%3Aserialized'],
  },
  {
    slug: 'secret-lair-serialized-295',
    title: 'Secret Lair Serialized /295',
    setCode: 'SLD',
    setName: 'Secret Lair Drop',
    releaseYear: 2023,
    releaseMonth: '2023-02 and later',
    treatment: 'serialized classic Secret Lair cards',
    trackingMode: 'promo-series',
    status: 'needs-verification',
    cardCount: 5,
    numbered: '1-295',
    foundIn: 'Random free gifts for MagicCon visitors',
    defaultSerialTotal: 295,
    sampleCards: ['Giant Growth', 'Lord of the Pit', 'Shivan Dragon'],
    scryfallQuery: 'set:sld is:serialized -!"Viscera Seer"',
    notes: 'Scryfall shows five classic Secret Lair serialized cards in addition to Viscera Seer.',
    sourceUrls: ['https://scryfall.com/search?q=set%3Asld+is%3Aserialized'],
  },
  {
    slug: 'mom-multiverse-legends',
    title: 'Multiverse Legends',
    setCode: 'MUL',
    setName: 'Multiverse Legends',
    releaseYear: 2023,
    releaseMonth: '2023-04',
    treatment: 'serialized double rainbow foil legends',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 65,
    numbered: '1-500',
    foundIn: 'Collector Boosters of March of the Machine',
    defaultSerialTotal: 500,
    sampleCards: ['Atraxa, Praetors\' Voice', 'Elesh Norn, Grand Cenobite', 'Ragavan, Nimble Pilferer'],
    scryfallQuery: 'set:mul is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Amul+is%3Aserialized'],
  },
  {
    slug: 'mom-serialized-praetors',
    title: 'March of the Machine Serialized Praetors',
    setCode: 'MOM',
    setName: 'March of the Machine',
    releaseYear: 2023,
    releaseMonth: '2023-04',
    treatment: 'serialized Praetor showcase cards',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 5,
    numbered: '1-500',
    foundIn: 'Collector Boosters of March of the Machine',
    defaultSerialTotal: 500,
    sampleCards: ['Elesh Norn // The Argent Etchings', 'Jin-Gitaxias // The Great Synthesis'],
    scryfallQuery: 'set:mom is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Amom+is%3Aserialized'],
  },
  {
    slug: 'lotr-one-ring-001',
    title: 'The One Ring 001/001',
    setCode: 'LTR',
    setName: 'The Lord of the Rings: Tales of Middle-earth',
    releaseYear: 2023,
    releaseMonth: '2023-06',
    treatment: 'unique serialized Quenya One Ring',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    numbered: '001/001',
    foundIn: 'Collector Boosters of The Lord of the Rings: Tales of Middle-earth',
    defaultSerialTotal: 1,
    sampleCards: ['The One Ring'],
    scryfallQuery: 'set:ltr is:serialized cn:0',
    sourceUrls: ['https://scryfall.com/card/ltr/0/the-one-ring'],
  },
  {
    slug: 'lotr-serialized-sol-rings',
    title: 'Serialized Sol Rings',
    setCode: 'LTC',
    setName: 'Tales of Middle-earth Commander',
    releaseYear: 2023,
    releaseMonth: '2023-06',
    treatment: 'Elven, Dwarven, and Human Sol Ring variants',
    trackingMode: 'variant-card',
    status: 'planned',
    cardCount: 3,
    numbered: 'Various',
    foundIn: 'Collector Boosters of The Lord of the Rings: Tales of Middle-earth',
    serialVariants: [
      { label: 'Elven Sol Ring', total: 300 },
      { label: 'Dwarven Sol Ring', total: 700 },
      { label: 'Human Sol Ring', total: 900 },
    ],
    sampleCards: ['Sol Ring'],
    scryfallQuery: 'set:ltc is:serialized "Sol Ring"',
    sourceUrls: ['https://scryfall.com/search?q=set%3Altc+is%3Aserialized+%22Sol+Ring%22'],
  },
  {
    slug: 'lotr-poster-cards',
    title: 'Serialized LOTR Poster Cards',
    setCode: 'LTR',
    setName: 'The Lord of the Rings: Tales of Middle-earth',
    releaseYear: 2023,
    releaseMonth: '2023-11',
    treatment: 'serialized borderless poster cards',
    trackingMode: 'multi-card-treatment',
    status: 'live',
    cardCount: 20,
    numbered: '1-100',
    foundIn: 'Collector Boosters of The Lord of the Rings Holiday Release',
    defaultSerialTotal: 100,
    sampleCards: ['The One Ring', 'Gandalf the White', 'Mount Doom'],
    scryfallQuery: 'set:ltr is:serialized cn>=731 cn<=750',
    notes: 'The current live One Ring tracker is the first single-card tracker from this treatment.',
    sourceUrls: ['https://scryfall.com/search?q=set%3Altr+is%3Aserialized'],
  },
  {
    slug: 'lotr-realms-and-relics',
    title: 'Serialized Realms and Relics',
    setCode: 'LTC',
    setName: 'Tales of Middle-earth Commander',
    releaseYear: 2023,
    releaseMonth: '2023-11',
    treatment: 'serialized Realms and Relics box toppers',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 30,
    numbered: '1-100',
    foundIn: 'Collector Boosters of The Lord of the Rings Holiday Release',
    defaultSerialTotal: 100,
    sampleCards: ['The Great Henge', 'Ancient Tomb', 'Wasteland'],
    scryfallQuery: 'set:ltc is:serialized -!"Sol Ring"',
    sourceUrls: ['https://scryfall.com/search?q=set%3Altc+is%3Aserialized'],
  },
  {
    slug: 'doctor-who-doctors',
    title: 'Serialized Doctors',
    setCode: 'WHO',
    setName: 'Doctor Who',
    releaseYear: 2023,
    releaseMonth: '2023-10',
    treatment: 'serialized showcase Doctors',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 13,
    numbered: '501-513 by Doctor',
    foundIn: 'Collector Boosters of Doctor Who',
    defaultSerialTotal: 500,
    sampleCards: ['The First Doctor', 'The Tenth Doctor', 'The Thirteenth Doctor'],
    scryfallQuery: 'set:who is:serialized',
    notes: 'The serialized total ranges from 501 to 513, matching each specific Doctor. Verify exact per-card totals before launch.',
    sourceUrls: ['https://scryfall.com/search?q=set%3Awho+is%3Aserialized'],
  },
  {
    slug: 'ravnica-remastered-retro-serials',
    title: 'Ravnica Remastered Retro Serials',
    setCode: 'RVR',
    setName: 'Ravnica Remastered',
    releaseYear: 2024,
    releaseMonth: '2024-01',
    treatment: 'serialized retro frame rares and mythics',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 64,
    numbered: '1-500',
    foundIn: 'Collector Boosters of Ravnica Remastered',
    defaultSerialTotal: 500,
    sampleCards: ['Birds of Paradise', 'Cyclonic Rift', 'Steam Vents'],
    scryfallQuery: 'set:rvr is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Arvr+is%3Aserialized'],
  },
  {
    slug: 'mkm-ravnica-city-showcase',
    title: 'Murders at Karlov Manor Ravnica City Serials',
    setCode: 'MKM',
    setName: 'Murders at Karlov Manor',
    releaseYear: 2024,
    releaseMonth: '2024-02',
    treatment: 'serialized double rainbow foil showcase cards',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 7,
    numbered: '1-250',
    foundIn: 'Collector Boosters of Murders at Karlov Manor',
    defaultSerialTotal: 250,
    sampleCards: ['Aurelia, the Law Above', 'Niv-Mizzet, Guildpact', 'Teysa, Opulent Oligarch'],
    scryfallQuery: 'set:mkm is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Amkm+is%3Aserialized'],
  },
  {
    slug: 'fallout-bobbleheads',
    title: 'Fallout Bobbleheads',
    setCode: 'PIP',
    setName: 'Fallout',
    releaseYear: 2024,
    releaseMonth: '2024-03',
    treatment: 'serialized bobblehead artifacts',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 7,
    numbered: '1-500',
    foundIn: 'Collector Boosters of Fallout',
    defaultSerialTotal: 500,
    sampleCards: ['Strength Bobblehead', 'Intelligence Bobblehead', 'Luck Bobblehead'],
    scryfallQuery: 'set:pip is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Apip+is%3Aserialized'],
  },
  {
    slug: 'assassins-creed-historical-figures',
    title: "Assassin's Creed Historical Figures",
    setCode: 'ACR',
    setName: "Assassin's Creed",
    releaseYear: 2024,
    releaseMonth: '2024-07',
    treatment: 'serialized historical figure showcase cards',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 4,
    numbered: '1-500',
    foundIn: "Collector Boosters of Assassin's Creed",
    defaultSerialTotal: 500,
    sampleCards: ['Leonardo da Vinci', 'Cleopatra, Exiled Pharaoh', 'Sokrates, Athenian Teacher'],
    scryfallQuery: 'set:acr is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Aacr+is%3Aserialized'],
  },
  {
    slug: 'mh3-concept-eldrazi',
    title: 'Modern Horizons 3 Concept Eldrazi',
    setCode: 'MH3',
    setName: 'Modern Horizons 3',
    releaseYear: 2024,
    releaseMonth: '2024-06',
    treatment: 'serialized concept Eldrazi titans',
    trackingMode: 'multi-card-treatment',
    status: 'planned',
    cardCount: 3,
    numbered: '1-250',
    foundIn: 'Collector Boosters of Modern Horizons 3',
    defaultSerialTotal: 250,
    sampleCards: ['Emrakul, the World Anew', 'Kozilek, the Broken Reality', 'Ulamog, the Defiler'],
    scryfallQuery: 'set:mh3 is:serialized',
    sourceUrls: ['https://scryfall.com/search?q=set%3Amh3+is%3Aserialized'],
  },
  {
    slug: 'innistrad-remastered-edgar-markov',
    title: 'Edgar Markov',
    setCode: 'INR',
    setName: 'Innistrad Remastered',
    releaseYear: 2025,
    releaseMonth: '2025-01',
    treatment: 'serialized movie poster card',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    numbered: '1-500',
    foundIn: 'Collector Boosters of Innistrad Remastered',
    defaultSerialTotal: 500,
    sampleCards: ['Edgar Markov'],
    scryfallQuery: 'set:inr is:serialized',
    sourceUrls: ['https://scryfall.com/card/inr/491/edgar-markov'],
  },
  {
    slug: 'aetherdrift-aetherspark',
    title: 'The Aetherspark',
    setCode: 'DFT',
    setName: 'Aetherdrift',
    releaseYear: 2025,
    releaseMonth: '2025-02',
    treatment: 'serialized headliner card',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    numbered: '1-500',
    foundIn: 'Collector Boosters of Aetherdrift',
    defaultSerialTotal: 500,
    sampleCards: ['The Aetherspark'],
    scryfallQuery: 'set:dft is:serialized',
    sourceUrls: ['https://scryfall.com/card/dft/376/the-aetherspark'],
  },
  {
    slug: 'tarkir-dragonstorm-mox-jasper',
    title: 'Mox Jasper',
    setCode: 'TDM',
    setName: 'Tarkir: Dragonstorm',
    releaseYear: 2025,
    releaseMonth: '2025-02',
    treatment: 'serialized headliner card',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    numbered: '1-500',
    foundIn: 'Collector Boosters of Tarkir: Dragonstorm',
    defaultSerialTotal: 500,
    sampleCards: ['Mox Jasper'],
    scryfallQuery: 'set:tdm is:serialized',
    sourceUrls: ['https://scryfall.com/card/tdm/419/mox-jasper'],
  },
  {
    slug: 'final-fantasy-traveling-chocobo',
    title: 'Traveling Chocobo',
    setCode: 'FIN',
    setName: 'Final Fantasy',
    releaseYear: 2025,
    treatment: 'golden serialized Traveling Chocobo',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    defaultSerialTotal: 77,
    sampleCards: ['Traveling Chocobo'],
    scryfallQuery: 'set:fin is:serialized',
    sourceUrls: ['https://scryfall.com/card/fin/551f/traveling-chocobo'],
  },
  {
    slug: 'secrets-of-strixhaven-emeritus',
    title: 'Emeritus of Ideation // Ancestral Recall',
    setCode: 'SOS',
    setName: 'Secrets of Strixhaven',
    releaseYear: 2026,
    treatment: 'serialized headliner card',
    trackingMode: 'single-card',
    status: 'planned',
    cardCount: 1,
    defaultSerialTotal: 500,
    sampleCards: ['Emeritus of Ideation // Ancestral Recall'],
    scryfallQuery: 'set:sos is:serialized',
    sourceUrls: ['https://scryfall.com/card/sos/306/emeritus-of-ideation-ancestral-recall'],
  },
  {
    slug: 'lorwyn-eclipsed-bitterbloom-bearer',
    title: 'Bitterbloom Bearer',
    setCode: 'ECL',
    setName: 'Lorwyn Eclipsed',
    releaseYear: 2026,
    treatment: 'serialized headliner card',
    trackingMode: 'single-card',
    status: 'announced',
    cardCount: 1,
    defaultSerialTotal: 500,
    sampleCards: ['Bitterbloom Bearer'],
    scryfallQuery: 'set:ecl is:serialized',
    sourceUrls: ['https://scryfall.com/card/ecl/352/bitterbloom-bearer'],
  },
  {
    slug: 'reality-fracture-bloodline-recollector',
    title: 'Bloodline Recollector // Ancestral Craving',
    setCode: 'FRA',
    setName: 'Reality Fracture',
    releaseYear: 2026,
    treatment: 'serialized headliner card',
    trackingMode: 'single-card',
    status: 'announced',
    cardCount: 1,
    defaultSerialTotal: 500,
    sampleCards: ['Bloodline Recollector // Ancestral Craving'],
    scryfallQuery: 'set:fra is:serialized',
    notes: 'Future/announced product data should be rechecked before launch.',
    sourceUrls: ['https://scryfall.com/card/fra/402/bloodline-recollector-ancestral-craving'],
  },
];

export const singleCardSerializedCatalog = serializedCatalog.filter(
  (entry) => entry.trackingMode === 'single-card'
);

export const multiCardSerializedCatalog = serializedCatalog.filter(
  (entry) => entry.trackingMode !== 'single-card'
);
